{"name": "test_login_failure", "status": "passed", "attachments": [{"name": "stdout", "source": "bd848aac-1396-4400-9222-c2c8df6c9a70-attachment.txt", "type": "text/plain"}], "start": 1749667847264, "stop": 1749667847595, "uuid": "d5d582ac-e36c-430a-97cb-c5754e06cfba", "historyId": "4038fcb77af2b80eea832d3a3633d3c6", "testCaseId": "4038fcb77af2b80eea832d3a3633d3c6", "fullName": "tests.views.test_auth_views#test_login_failure", "labels": [{"name": "parentSuite", "value": "tests.views"}, {"name": "suite", "value": "test_auth_views"}, {"name": "host", "value": "PC-5CG4282G66"}, {"name": "thread", "value": "20736-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.views.test_auth_views"}]}