{"name": "test_login_notfounduser", "status": "passed", "attachments": [{"name": "stdout", "source": "c08af554-a6bb-429c-9a0c-5e94ac5a23d8-attachment.txt", "type": "text/plain"}], "start": 1749496567025, "stop": 1749496567033, "uuid": "c6857d1a-58df-46b7-b687-7aa2cf4c8c10", "historyId": "857ff9e2b048d3a4ec2d51d8ea12cb3d", "testCaseId": "857ff9e2b048d3a4ec2d51d8ea12cb3d", "fullName": "tests.views.test_auth_views#test_login_notfounduser", "labels": [{"name": "parentSuite", "value": "tests.views"}, {"name": "suite", "value": "test_auth_views"}, {"name": "host", "value": "PC-5CG4282G66"}, {"name": "thread", "value": "38368-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.views.test_auth_views"}]}